"""empty message

Revision ID: 12ef38410d99
Revises: 56d5b9ebee74
Create Date: 2016-03-29 00:35:19.428294

"""

# revision identifiers, used by Alembic.
revision = '12ef38410d99'
down_revision = '56d5b9ebee74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('selected_rating')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_rating',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name=u'selected_rating_event_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], [u'users.id'], name=u'selected_rating_users_id_fkey')
    )
    op.drop_table('rating')
    ### end Alembic commands ###
