"""empty message

Revision ID: 56d5b9ebee74
Revises: 677af2a549d0
Create Date: 2016-03-28 21:11:22.443656

"""

# revision identifiers, used by Alembic.
revision = '56d5b9ebee74'
down_revision = '677af2a549d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected_rating',
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    op.drop_table('rating')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], name=u'rating_event_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], [u'users.id'], name=u'rating_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'rating_pkey')
    )
    op.drop_table('selected_rating')
    ### end Alembic commands ###
