"""empty message

Revision ID: 677af2a549d0
Revises: None
Create Date: 2016-03-28 20:37:09.645413

"""

# revision identifiers, used by Alembic.
revision = '677af2a549d0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'rate',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'rate',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
