"""empty message

Revision ID: 76e55d3e06eb
Revises: 9f1f85ca8a70
Create Date: 2016-05-13 02:11:52.860179

"""

# revision identifiers, used by Alembic.
revision = '76e55d3e06eb'
down_revision = '9f1f85ca8a70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'timestamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
