"""empty message

Revision ID: be371e0ba082
Revises: adbe4df186d8
Create Date: 2016-05-07 04:56:39.293640

"""

# revision identifiers, used by Alembic.
revision = 'be371e0ba082'
down_revision = 'adbe4df186d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'card', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'user_id')
    ### end Alembic commands ###
