"""empty message

Revision ID: fbb9bb2e95ee
Revises: 4f49f2c33b3d
Create Date: 2016-05-06 08:16:39.014860

"""

# revision identifiers, used by Alembic.
revision = 'fbb9bb2e95ee'
down_revision = '4f49f2c33b3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.String(length=12), nullable=True),
    sa.Column('card_num', sa.Integer(), nullable=True),
    sa.Column('card_cvv', sa.Integer(), nullable=True),
    sa.Column('expire_month', sa.String(length=10), nullable=True),
    sa.Column('expire_year', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    ### end Alembic commands ###
